steps:

- id: "Rodando o teste unitário"
  name: gcr.io/cloud-builders/go
  env: ["GOPATH=."]
  dir: "./src"
  args: ['test']

- id: "Rodando o app"
  name: gcr.io/cloud-builders/go
  env: ["GOPATH=."]
  dir: "./src"
  args: ['run','soma.go']

- id: "Fazendo o Build"
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/desafio-go-ci'
  - '.'

images: 
  - 'gcr.io/$PROJECT_ID/desafio-go-ci'